#!/usr/bin/env python3
"""Convert Pupul Equinox demo GIFs into a C++ header.

Each GIF is read as palette-indexed (one byte per pixel) plus an RGB565
palette LUT. The transparent index (if any) is captured so sprite blits
can skip those pixels.

Inputs : tools/demoref/equinox/pupul/assets/*.gif
Output : src/demos/pupul_assets.h
"""

from __future__ import annotations
import os
import sys
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASSETS_DIR = os.path.join(ROOT, "tools/demoref/equinox/pupul/assets")
HEADER_PATH = os.path.join(ROOT, "src/demos/pupul_assets.h")

# (struct-name, gif-filename)
ASSETS = [
    ("kFondMain", "fondpupul2.gif"),
    ("kFondStrip", "fondpupul22.gif"),
    ("kFont", "fonte.gif"),
    ("kDragon1", "dragon1.gif"),
    ("kDragon2", "dragon2.gif"),
    ("kDragon3", "dragon3.gif"),
    ("kDragon4", "dragon4.gif"),
    ("kDragon5", "dragon5.gif"),
    ("kDragon6", "dragon6.gif"),
    ("kDragon7", "dragon7.gif"),
    ("kDragon8", "dragon8.gif"),
]


def rgb_to_rgb565(r: int, g: int, b: int) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def read_indexed(path: str):
    img = Image.open(path)
    if img.mode != "P":
        # Some GIF decoders return RGBA; force palette mode.
        img = img.convert("P")
    width, height = img.size
    raw_palette = img.getpalette() or []
    # Pad palette to 256 entries × 3 bytes.
    raw_palette = raw_palette + [0] * (256 * 3 - len(raw_palette))
    palette565 = [
        rgb_to_rgb565(raw_palette[i * 3], raw_palette[i * 3 + 1], raw_palette[i * 3 + 2])
        for i in range(256)
    ]
    pixels = list(img.getdata())
    transparent = img.info.get("transparency")
    if transparent is None:
        transparent = 0xFF  # sentinel — "no transparency"
    return pixels, palette565, width, height, int(transparent)


def write_array(fp, name: str, values, formatter, per_row: int):
    fp.write(f"const {formatter.dtype} {name}[] = {{\n  ")
    for i, v in enumerate(values):
        fp.write(formatter.fmt(v))
        fp.write(",")
        if (i + 1) % per_row == 0 and i + 1 != len(values):
            fp.write("\n  ")
    fp.write("\n};\n\n")


class Fmt:
    def __init__(self, dtype, fn):
        self.dtype = dtype
        self.fmt = fn


U8_DEC = Fmt("uint8_t", lambda v: f"{v:3d}")
U16_HEX = Fmt("uint16_t", lambda v: f"0x{v:04x}")


def emit_asset(fp, name: str, gif_path: str):
    pixels, palette565, w, h, transparent = read_indexed(gif_path)
    fp.write(f"// {os.path.basename(gif_path)} — {w}×{h}, transparent index={transparent}\n")
    write_array(fp, f"{name}_pixels", pixels, U8_DEC, per_row=32)
    write_array(fp, f"{name}_palette", palette565, U16_HEX, per_row=12)
    fp.write(
        f"const IndexedSprite {name} = {{\n"
        f"    {name}_pixels,\n"
        f"    {name}_palette,\n"
        f"    {w},\n"
        f"    {h},\n"
        f"    {transparent},\n"
        f"}};\n\n"
    )
    return w * h, len(palette565) * 2


def main() -> int:
    os.makedirs(os.path.dirname(HEADER_PATH), exist_ok=True)
    total_pixels = 0
    total_palettes = 0
    with open(HEADER_PATH, "w") as fp:
        fp.write(
            "// Auto-generated by tools/convert_pupul_assets.py — DO NOT EDIT.\n"
            "// Bakes the Equinox Pupul GIFs into palette-indexed sprites.\n"
            "// See tools/demoref/equinox/pupul/PORT_NOTES.md for the spec.\n\n"
            "#pragma once\n\n"
            "#include <stdint.h>\n\n"
            "namespace pupul_assets {\n\n"
            "struct IndexedSprite {\n"
            "  const uint8_t *pixels;     // row-major palette indices\n"
            "  const uint16_t *palette;   // 256 × RGB565\n"
            "  uint16_t width;\n"
            "  uint16_t height;\n"
            "  uint8_t transparentIdx;    // 0xFF = no transparency\n"
            "};\n\n"
            "namespace data {\n\n"
        )
        for name, gif_name in ASSETS:
            p, pal = emit_asset(fp, name, os.path.join(ASSETS_DIR, gif_name))
            total_pixels += p
            total_palettes += pal
        fp.write("}  // namespace data\n\n")
        fp.write(
            "// Public table of the 8 dragon animation frames so the renderer\n"
            "// can index by current frame (1..8 → 0..7).\n"
            "constexpr const IndexedSprite *const kDragon[8] = {\n"
        )
        for i in range(1, 9):
            fp.write(f"  &data::kDragon{i},\n")
        fp.write("};\n\n")
        fp.write("constexpr const IndexedSprite &kFondMain  = data::kFondMain;\n")
        fp.write("constexpr const IndexedSprite &kFondStrip = data::kFondStrip;\n")
        fp.write("constexpr const IndexedSprite &kFont      = data::kFont;\n\n")
        fp.write("}  // namespace pupul_assets\n")
    print(
        f"wrote {HEADER_PATH}: {total_pixels} pixels, "
        f"{total_palettes} palette bytes, ≈{(total_pixels + total_palettes) // 1024} KB"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
